### ISSUE TITLE
关于CPU占用问题

### ISSUE THREAD

**Issue by llatecomers** [waterfoxfox/HWcodec#1]
你好，首先很感谢UP主，上传该份源码，对我刚开始接触windows视频开发有很大作用，感谢。
其次，在对比HWcodec中qsv硬件编码和X264软件编码,在码率、帧率、视频画面一样的情况下进行二者之间的比较，qsv相对于x264在CPU占用率(%10)变化不大甚至更高，GPU占用6%。
在OBS软件上面对比X264和qsv硬件编码，qsv的cpu占用明显降低。
OBS X264：画面静态：6.6% ，画面动态：19%
OBS qsv：画面静态：2.2%  GPU : 13% ，画面动态：2.7%  GPU:17~22%

请问基于FFMEPG的qsv有办法做到与obs在CPU上面相同的效果？

**Comment by llatecomers** [comment]
经过一天的研究，CPU占用主要来自BmpZoom中scale格式转换，前端采集的数据为RGB格式，而qsv_h264似乎只支持默认NV12格式，设置指定格式无效。不知道有没有什么好的办法。

**Comment by xiaozhishang** [comment]
> 经过一天的研究，CPU占用主要来自BmpZoom中scale格式转换，前端采集的数据为RGB格式，而qsv_h264似乎只支持默认NV12格式，设置指定格式无效。不知道有没有什么好的办法。

h264_qsv的确是只支持NV12，要是换成其它如YUV420p就直接报错了。想请问一下，有没有遇到过h264_qsv编码的视频的高度设置为1536，然后内存占用特别高的情况。但把视频高度设置为1535或者1537就正常，定位到avcodec_encode_video2()函数

**Comment by waterfoxfox** [comment]
这里的颜色空间转换使用的ffmpeg，确实性能一般，建议换成libyuv试试
